### ISSUE TITLE
JsonParameterProcessor::ProcessParameters fails when different objects share property names

### ISSUE THREAD

**Issue by edrd-d** [aws/aws-dotnet-extensions-configuration#123] opened 2022-11-08 14:04 UTC
### Describe the bug

JsonParameterProcessor::ProcessParameters fails when different objects share property names.

### Expected Behavior

Process duplicated property names, since they belong to different objects.

### Current Behavior

Considering these two different parameters, both containing objects with same properties and different values:

```
/release/api/ObjectA { "Bucket": "arnA" }
/release/api/ObjectB { "Bucket": "arnB" }
```

JsonParameterProcessor throws `System.ArgumentException: An item with the same key has already been added`.

### Reproduction Steps

Configure AddSystemManager:

```
builder.Configuration.AddSystemsManager(source =>
{
    source.ParameterProcessor = new JsonParameterProcessor();
    source.Path = $"/release/api";
});
```

Create two parameter:

```
/release/api/ObjectA { "Bucket": "arnA" }
/release/api/ObjectB { "Bucket": "arnB" }
```

Map those parameters into objects:

```
public abstract class AbstractSettings
{
    public string Bucket { get; init; }
}

public class ObjectA: AbstractSettings {}

public class ObjectB: AbstractSettings {}
```

Call Services.Configure:

```
builder.Services.Configure<ObjectA>(builder.Configuration.GetSection("ObjectA"));
builder.Services.Configure<ObjectB>(builder.Configuration.GetSection("ObjectB"));
```

I expect System.ArgumentException during the second call to Services.Configure.

### AWS .NET SDK and/or Package version used

AWSSDK.SimpleSystemsManagement 3.7.12.9
Amazon.Extensions.Configuration.SystemsManager 4.0.0
AWSSDK.Extensions.NETCore.Setup 3.7.1

### Targeted .NET Platform

.NET 6.0

### Operating System and version

OSX Ventura

**Comment by ashishdhingra** [comment] 2022-11-11 17:05
Reproducible using customer's code.

**Comment by ashishdhingra** [comment] 2023-01-31 22:14
The reason why the customer's scenarios fails is that it tries to process the parameter value that starts with path that begins with `/release/api` and convert it to `Dictionary` at https://github.com/aws/aws-dotnet-extensions-configuration/blob/e60c16d143ce38ac6b15233d6f1b447ececce862/src/Amazon.Extensions.Configuration.SystemsManager/JsonParameterProcessor.cs#L35

Here, it would first process JSON value for parameter for path `/release/api/ObjectA` and add value with key `Bucket` to dictionary. When it proceeds to process JSON value for parameter for path `/release/api/ObjectB`, duplicate key `Bucket` is added and hence exception is thrown.

The desired fix might be to path separate parameters by remaining path segment (e.g. `ObjectA` or `ObjectB` or `somepath/ObjectA`) using configuration builder convention (which is to separate parameter path with `:` separator), but would not work for issue reported in the case. It's the `JsonParameterProcessor`, not the JsonParameterDeserializer.

**Comment by ashishdhingra** [comment] 2023-02-08 00:12
Fixed in [Amazon.Extensions.Configuration.SystemsManager version 5.0.0](https://www.nuget.org/packages/Amazon.Extensions.Configuration.SystemsManager/5.0.0). Kindly take note of the **breaking change** entry in [RELEASE.CHANGELOG.md](https://github.com/aws/aws-dotnet-extensions-configuration/blob/master/RELEASE.CHANGELOG.md).

**Closed by ashishdhingra** 2023-02-08 00:12 UTC
Labels: bug, module/sys-mgr-ext, p1, queued
