### ISSUE TITLE
ReloadAfter doesn't work in Lambda

### ISSUE THREAD

**Issue by LouisCC-1** [aws/aws-dotnet-extensions-configuration#67] opened 2020-05-18 10:11 UTC
The ReloadAfter functionality in SystemsManagerConfigurationProvider doesn't work if the code runs in AWS Lambda. Parameter values remain the same during the lifetime of the Lambda instance

See also https://github.com/aws/aws-dotnet-extensions-configuration/issues/17 

This is a Bug not a Feature-Request

**Comment by ashishdhingra** [comment] 2020-10-23 20:25
Closing this as duplicate of https://github.com/aws/aws-dotnet-extensions-configuration/issues/17

**Closed** 2020-10-23 20:26 UTC
Labels: bug, duplicate, module/sys-mgr-ext, needs-reproduction
