### ISSUE TITLE
NotImplementedException - application/json; charset=utf-8

### ISSUE THREAD

**Issue by BrettBock** [aws/aws-dotnet-extensions-configuration#132] opened 2023-02-26 14:30 UTC
### Describe the bug

Using .NET 6
Getting NotImplementedException when calling `Amazon.Extensions.Configuration.SystemsManager.AddSource()`

### Expected Behavior

Expected the json file to be parsed and available to the .NET Docker microservice via IConfiguration.

### Current Behavior

Getting the error below when connecting to an AppConfig json file.  Looking at the code, application/json should be the only file type allowed.  Is there are required charset type?

```
System.NotImplementedException
  HResult=0x80004001
  Message=Not implemented AppConfig type: application/json; charset=utf-8
  Source=Amazon.Extensions.Configuration.SystemsManager
  StackTrace:
   at Amazon.Extensions.Configuration.SystemsManager.AppConfig.AppConfigProcessor.ParseConfig(String contentType, Stream configuration)
   at Amazon.Extensions.Configuration.SystemsManager.AppConfig.AppConfigProcessor.<GetDataFromServiceAsync>d__23.MoveNext()
   at Amazon.Extensions.Configuration.SystemsManager.AppConfig.AppConfigProcessor.<GetDataAsync>d__21.MoveNext()
   at Amazon.Extensions.Configuration.SystemsManager.SystemsManagerConfigurationProvider.<LoadAsync>d__14.MoveNext()
   at Amazon.Extensions.Configuration.SystemsManager.SystemsManagerConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationManager.AddSource(IConfigurationSource source)
   at Microsoft.Extensions.Configuration.ConfigurationManager.Microsoft.Extensions.Configuration.IConfigurationBuilder.Add(IConfigurationSource source)
```

### Reproduction Steps

Code below actually was using personal ids, but changed for example:
```
using Microsoft.AspNetCore.Rewrite;
using Microsoft.OpenApi.Models;
using System.Runtime.CompilerServices;

var builder = WebApplication.CreateBuilder(args);

builder.Configuration
    .AddAppConfig(
        applicationId: "applicationId",
        environmentId: "environmentId",
        configProfileId: "configProfileId",
        // optional: true, // using true keeps exception from happening
        reloadAfter: TimeSpan.FromSeconds(20));
```

### AWS .NET SDK and/or Package version used

![image](https://user-images.githubusercontent.com/6113371/221416509-3823de11-bdef-4a55-9a11-cae1ec074cf4.png)

### Targeted .NET Platform

.NET 6

### Operating System and version

Windows 11, and on AWS as microservice

**Comment by BrettBock** [comment] 2023-03-05 12:27
While creating some sample code, I believe I discovered an issue.  The configuration we had in AWS used AppConfig's Freeform Configuration with Amazon S3 Object.  By switching to AWS AppConfig hosted configuration with JSON content, the code is now working.

Are there known issues with using S3 and AppConfig?  Should a separate issue be created for working with an Amazon S3 Object?

Thank you for your help, and working this project.

**Comment by ashishdhingra** [comment] 2023-03-08 22:08
> While creating some sample code, I believe I discovered an issue. The configuration we had in AWS used AppConfig's Freeform Configuration with Amazon S3 Object. By switching to AWS AppConfig hosted configuration with JSON content, the code is now working.
> 
> Are there known issues with using S3 and AppConfig? Should a separate issue be created for working with an Amazon S3 Object?
> 
> Thank you for your help, and working this project.

@BrettBock Somehow I'm unable to reproduce the issue. Below are the steps I followed:
- Created a new bucket with versioning enabled (AppConfig with S3 object source requires S3 bucket with versioning enabled).
- Created below `test-app-config.json`:
```JSON
{
    "name": "test",
    "type": "document",
    "test": "value"
}
```
- In AppConfig AWS console, created a new freeform configuration profile with S3 object as source.
- Deployed the configuration
- In the ASP.NET application, used code `builder.Configuration.AddAppConfig("<<application-id>>", "<<environment-id>>", "<<config-profile-id>>", TimeSpan.FromSeconds(30));`

**RESULT:** I was able to retrieve the app configuration. the content type as reported at [AppConfigProcessor.ParseConfig()](https://github.com/aws/aws-dotnet-extensions-configuration/blob/57a04c8ce00413fb0f420480ba3afe364c8dbb31/src/Amazon.Extensions.Configuration.SystemsManager/AppConfig/AppConfigProcessor.cs#L166) is `application/json`
- Checked the system-defined `Content-Type` metadata for JSON file uploaded in S3 bucket. It is listed as `application/json`.

Could you please:
- Check the content type of the file at your end?
- How is that JSON file in your case uploaded? Is it by some automated process which sets the `Content-Type` metadata during upload?

While it would not be a good idea to manually change the `Content-Type` metadata for S3 object, the simple fix could be to compare only the 1st part before `;` in the content type at at [AppConfigProcessor.ParseConfig()](https://github.com/aws/aws-dotnet-extensions-configuration/blob/57a04c8ce00413fb0f420480ba3afe364c8dbb31/src/Amazon.Extensions.Configuration.SystemsManager/AppConfig/AppConfigProcessor.cs#L166) since the content-type could have extra information.

Thanks,
Ashish

**Comment by BrettBock** [comment] 2023-03-10 10:54
I would agree that using just the first part of the `content-type` would be a good fix, since as far as I know the parser is not dependent on the encoding.

On my end:
- By changing the S3 Metadata for Content-Type to only application/json, we are able to use the S3 file.
- We have been using Visual Studio Code with the AWS toolkit to create and edit the S3 files.
- Using VSCode to save the file the first time adds the additional encoding.
- Changing the S3 Metadata appears to stick, so that future edits can be done.

Again, thank you for your help, and working this project.

**Comment by ashishdhingra** [comment] 2023-03-21 21:04
This has been fixed in [Amazon.Extensions.Configuration.SystemsManager version 5.0.2](https://www.nuget.org/packages/Amazon.Extensions.Configuration.SystemsManager/5.0.2).

**Closed by ashishdhingra** 2023-03-21 21:04 UTC
Labels: bug, module/sys-mgr-ext, queued, p2
